#!/bin/bash

trap ctrl_c INT

function ctrl_c() {
        printf '\nBye!\n'
        rm ping_temp nmap_temp $out
        exit 1
} 2>/dev/null

function help() {
	echo 'usage: p0rtscan [-d] [-p] host'
	echo ''
	echo 'optimized nmap scan useful for pentesting, ctfs, etc'
	echo ''
	echo 'options:'
	echo -e '  -d\tdefault scan'
	echo -e '  -p\tproxy scan'
	echo ''
}

if [ -z $2 ]
then
	help
	exit 1
fi

while getopts ':dp' opt
do
	case $opt in
		d)
			echo '[*] DEFAULT SCAN'
			echo ''
			echo '[*] Pinging target...'
			ping -c 5 $2 | grep ttl | cut -f6 -d ' ' > ping_temp
			if grep -q '64\|63\|62\|61' ping_temp
			then
			        echo 'Target is UP'
			        echo 'Target is likely LINUX'

			elif grep -q '128\|127\|126\|125' ping_temp
			then
			        echo 'Target is UP'
			        echo 'Target is likely WINDOWS'
			elif grep -q '255\|254\|253\|252' ping_temp
			then
			        echo 'Target is UP'
			        echo 'Target is likely OTHER'
			else
			        echo 'Target not responding to ping'
			        rm ping_temp
			        exit 1
			fi
			rm ping_temp
			echo ''

			echo '[*] Scanning all ports...'
			nmap -v $2 -p- -oN nmap_temp | grep Discovered
			ports=$(cat nmap_temp | grep tcp | cut -f1 -d '/' | tr '\n' ',')
			rm nmap_temp
			echo ''

			echo '[*] Starting detailed scan...'
			sleep 1
			out=$(echo nmap-$2)
			nmap $2 -p $ports -sCV -oN $out
		;;
		p)
			echo '[*] PROXY SCAN'
                        echo ''
			echo '[*] Scanning common ports...'
			proxychains nmap -Pn -sT -v $2 -oN nmap_temp 2>/dev/null | grep Discovered
			ports=$(cat nmap_temp | grep tcp | cut -f1 -d '/' | tr '\n' ',')
			rm nmap_temp
			echo ''

			echo '[*] Starting detailed scan...'
			sleep 1
			out=$(echo nmap-$2)
			proxychains nmap -Pn -sTCV $2 -p $ports -oN $out 2>/dev/null
		;;
		\?)
			help
		;;
	esac
done
